import { AdminSettings, CustomerFeedback, CustomerLead, GoldRatesConfig } from "../types/admin";

export const DEFAULT_RATES: GoldRatesConfig = {
  "24K": 7850,
  "22K": 7210,
  "20K": 6550,
  "18K": 5910,
  silver: 94,
};

export const DEFAULT_SETTINGS: AdminSettings = {
  phone: "+91 81011 21813",
  whatsapp: "918101121813",
  bowbazarAddress: "Kalyani & Bidhannagar",
  gariahatAddress: "Newtown",
  adminPin: "8101",
};

export const SAMPLE_LEADS: CustomerLead[] = [
  {
    id: "lead-1",
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    name: "Subhashis Roy",
    phone: "9830145210",
    location: "Kalyani",
    serviceType: "Gold Loan Settlement",
    category: "auction_relief",
    goldGrams: "65g",
    loanAmount: 240000,
    lender: "Muthoot Finance",
    status: "New",
    notes: "Auction notice received, urgent release required",
    attachment: {
      name: "muthoot_auction_notice.pdf",
      size: "620 KB",
      isImage: false,
      type: "document",
    },
  },
  {
    id: "lead-2",
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    name: "Ananya Mukherjee",
    phone: "9831088452",
    location: "Bidhannagar",
    serviceType: "Gold Loan Settlement",
    category: "gold_loan",
    goldGrams: "90g",
    loanAmount: 180000,
    lender: "Manappuram Finance",
    status: "Contacted",
    notes: "Wants to sell only 25g to clear entire loan and take remaining home",
    attachment: {
      name: "manappuram_pledge_slip.jpg",
      size: "480 KB",
      isImage: true,
      type: "document",
    },
  },
  {
    id: "lead-3",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    name: "Debashis Banerjee",
    phone: "9874123560",
    location: "Newtown",
    serviceType: "Sell Old Gold & Jewellery",
    category: "old_gold",
    goldGrams: "34g",
    loanAmount: 0,
    lender: "Physical Gold",
    status: "Settled",
    notes: "Old hallmarked bangles sold at custom rate",
    attachment: {
      name: "gold_bangles_photo.jpg",
      size: "1.2 MB",
      isImage: true,
      type: "photo",
    },
  },
  {
    id: "lead-4",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    name: "Rajesh Sen",
    phone: "9830219844",
    location: "Kolkata",
    serviceType: "Sell Old Gold & Jewellery",
    category: "old_gold",
    goldGrams: "28g",
    loanAmount: 0,
    lender: "Physical Gold",
    status: "Verified",
    notes: "22K gold chain and ring appraisal",
  },
];

export const SAMPLE_FEEDBACKS: CustomerFeedback[] = [
  {
    id: "fb-1",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    name: "Arijit Ghosh",
    phone: "98302XXXXX",
    location: "Kalyani",
    serviceType: "Gold Loan Settlement",
    rating: 5,
    comment: "Muthoot auction notice aa chuka tha aur interest har mahine double ho raha tha. Subah call kiya, 2 baje unka representative branch aaya. Samne paper sign hua aur locker se jewellery direct mere haath me mili. Bacha liya inhone.",
    recommended: true,
  },
  {
    id: "fb-2",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    name: "Sharmistha Mukherjee",
    phone: "98311XXXXX",
    location: "Bidhannagar",
    serviceType: "Bank Gold Release",
    rating: 5,
    comment: "Ekdom genuine experience. First e ektu doubt chhilo kivabe third party diye bank theke sona chhadano hoy. But sob paper samne verify holo, zero extra charge nilo na. Khub bhalo service.",
    recommended: true,
  },
  {
    id: "fb-3",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    name: "Vikramaditya Singhania",
    phone: "98745XXXXX",
    location: "Newtown",
    serviceType: "Gold Loan Settlement",
    rating: 4,
    comment: "Valuation process transparent tha aur rate market se behtar mila. Bank counter pe paperwork me thoda 35-40 min time zyada lag gaya crowd ki wajah se, but overall very safe and professional settlement.",
    recommended: true,
  },
  {
    id: "fb-4",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    name: "Subrata Dey",
    phone: "98004XXXXX",
    location: "Kalyani",
    serviceType: "Loan Settlement & Cash Back",
    rating: 5,
    comment: "Manappuram e 42 gram sona girvi chhilo 1.5 bochhor dhore. Chhadanor moto puro taka chhiloba na. Era bank e giye direct settle kore dilo, extra 18,500 taka cash o pelam haate. Khub upokar holo.",
    recommended: true,
  },
  {
    id: "fb-5",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    name: "Puja Agarwal",
    phone: "98319XXXXX",
    location: "Newtown",
    serviceType: "Sell Old Gold & Jewellery",
    rating: 5,
    comment: "Mom's old broken chains aur 2 heavy bangles sell kiye. Pehle dusre local sunar ne 12% melting loss bola tha, yaha computerized testing me 0% deduction aur live 22K rate mila. Instant NEFT payout.",
    recommended: true,
  },
  {
    id: "fb-6",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    name: "Debabrata Roy",
    phone: "94331XXXXX",
    location: "Bidhannagar",
    serviceType: "SBI Gold Loan Release",
    rating: 5,
    comment: "SBI gold loan close korlam. Shobcheye bhalo laglo kono advance taka age theke chaie ni. Branch er shamne bose hisheb holo ar locker theke sona direct ami nije collect korlam.",
    recommended: true,
  },
  {
    id: "fb-7",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    name: "Rajesh K. Sharma",
    phone: "98305XXXXX",
    location: "Kalyani",
    serviceType: "Sell Old Gold",
    rating: 4,
    comment: "Staff polite tha aur weighing scale certified tha. Rate fair mila. First time phone connect hone me thoda delay hua tha but call-back karke same day pure transparency ke saath kaam karwa diya.",
    recommended: true,
  },
  {
    id: "fb-8",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21).toISOString(),
    name: "Moumita Banik",
    phone: "98317XXXXX",
    location: "Newtown",
    serviceType: "Partial Gold Release",
    rating: 5,
    comment: "Partial release option ta amar jonno life-saver chhilo. 70 gram er moddhe 22 gram bikri kore puro bank loan shodh hoye gelo, baki wedding necklace ta bari niye chole ashlam. Thank you so much!",
    recommended: true,
  },
  {
    id: "fb-9",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    name: "Anupam Sen",
    phone: "98300XXXXX",
    location: "Bidhannagar",
    serviceType: "Fedbank Loan Settlement",
    rating: 5,
    comment: "Fedbank gold loan release karwaya. Manager ke samne settlement draft jama kiya aur physical gold mere samne seal open karke diya. No hidden deductions, honest log hain.",
    recommended: true,
  },
  {
    id: "fb-10",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    name: "Tanmay Haldar",
    phone: "98008XXXXX",
    location: "Kalyani",
    serviceType: "Spot Cash for Old Gold",
    rating: 5,
    comment: "Emergency medical expense er jonno purano sona bikri korte hoyechhilo. Eder counter e khub fast 20 min er moddhe computer checking kore spot cash & UPI transfer kore dilo. Genuine service.",
    recommended: true,
  },
];


